#include "canvas/Persistency/Common/Wrapper.h"
#include "canvas/Persistency/Common/Assns.h"
#include "sbnobj/SBND/Trigger/pmtTrigger.hh"
#include "sbnobj/SBND/Trigger/pmtSoftwareTrigger.hh"
#include "sbnobj/SBND/Trigger/CRTmetric.hh"
#include "sbnobj/SBND/Trigger/Coincidence.hh"
#include <vector>
#include <map>
#include <utility>
